### YamlMime:Lifecycle
metadata:
  title: Microsoft Intelligent Application Gateway 2007
  description: O Microsoft Intelligent Application Gateway 2007 segue a Política do Ciclo de Vida Fixa.
  ms.date: 07/28/2020
  ms.openlocfilehash: 2e4cb68a2f1b63fbdc64507b9b16fbdc2f8008a0
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: pt-PT
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4114641"
name: Microsoft Intelligent Application Gateway 2007
summary: >
  O Microsoft Intelligent Application Gateway 2007 segue a Política do Ciclo de Vida [Fixa](/lifecycle/policies/fixed).



  > [!IMPORTANT]

  > O suporte para este produto terminou. Ver abaixo as orientações sobre migração.
products:
- microsoft-servers
policyType: fixed
supportDates:
  start: 2007-06-01T00:00:00.000-08:00
  end: 2012-07-10T22:59:59.999-08:00
  extendedEnd: 2017-07-11T22:59:59.999-08:00
releases:
- version: Service Pack 2
  startDate: 2008-11-27T00:00:00.000-08:00
  endDate: 2017-07-11T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2007-09-03T00:00:00.000-08:00
  endDate: 2010-01-12T22:59:59.999-08:00
- version: Original Release
  startDate: 2007-06-01T00:00:00.000-08:00
  endDate: 2008-10-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Ligações \n* [Mapa de Objetivos do Microsoft Intelligent Application Gateway 2007](/archive/blogs/testtesttestbug/important-changes-to-the-forefront-product-line)\n* [Política do service pack](/lifecycle/policies/fixed#service-packs)"
