### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.6 para Ambientes de Trabalho Windows
  description: O Microsoft Application Virtualization Hosting 4.6 para Ambientes de Trabalho do Windows segue a Política de Ciclo de Vida Fixa.
  ms.date: 07/28/2020
  ms.openlocfilehash: 21ed557cd6333e43a274796a3b25791c0d7f96cd
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: HT
  ms.contentlocale: pt-PT
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "833472"
name: Microsoft Application Virtualization Hosting 4.6 para Ambientes de Trabalho Windows
summary: >+
  O Microsoft Application Virtualization Hosting 4.6 para Ambientes de Trabalho do Windows segue a Política de Ciclo de Vida [Fixa](/lifecycle/policies/fixed).


  Isto aplica-se às seguintes edições: para Ambientes de Trabalho do Windows

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Ligações \n* [Informação sobre o produto e migração](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Política do service pack](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Como o cliente App-V 4.6 utiliza o App-V 4.5 Server, o App-V 4.5 Server continuará a ser suportado de acordo com as datas do ciclo de vida do App-V 4.6 quando for usado com o cliente App-V 4.6 suportado.\n\n## <a name=\"editions\"></a>Edições \n* para Windows Desktops"
