### YamlMime:Lifecycle
metadata:
  title: Gestor de Configuração do Microsoft System Center 2012
  description: O Gestor de Configuração do Microsoft System Center 2012 segue a Política de Ciclo de Vida Fixa.
  ms.date: 03/12/2021
  keywords: 
  ms.openlocfilehash: b550f4d818fcc32d871457dc01fc4d0a93149c7d
  ms.sourcegitcommit: 8465b0fa45ee2c451d1f1eaf7be9a1544cdad17f
  ms.translationtype: HT
  ms.contentlocale: pt-PT
  ms.lasthandoff: 03/12/2021
  ms.locfileid: "1462955"
name: Gestor de Configuração do Microsoft System Center 2012
summary: >+
  O Gestor de Configuração do Microsoft System Center 2012 segue a Política de Ciclo de Vida [Fixa](/lifecycle/policies/fixed).


products:
- msc
policyType: fixed
supportDates:
  start: 05/30/2012
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
- version: Service Pack 2
  startDate: 05/12/2015
  endDate: 07/12/2022
- version: Service Pack 1
  startDate: 12/15/2012
  endDate: 07/12/2016
- version: Original Release
  startDate: 05/30/2012
  endDate: 01/14/2014
content: "\n## <a name=\"links\"></a>Ligações \n* [Política do service pack](/lifecycle/policies/fixed#service-packs)\n* [Documentação do System Center](/system-center/#pivot=components&panel=components-all)\n* [Recursos do System Center](https://www.microsoft.com/system-center/resources)\n* [Orientações sobre migração](https://techcommunity.microsoft.com/t5/configuration-manager-blog/system-center-2012-configuration-manager-is-approaching-end-of/ba-p/1650899)"
