### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 4.6
  description: O Microsoft Application Virtualization 4.6 segue a Política de Ciclo de Vida Fixa.
  ms.date: 09/01/2020
  keywords: for Remote Desktop Services,for Windows Desktops,Sequencer
  ms.openlocfilehash: e7ee52090b6e77209d2cc75b5862c21dfe4fe3dd
  ms.sourcegitcommit: af46dd09ccdabd80dcc49d2cd930cefa0b1ab8a6
  ms.translationtype: HT
  ms.contentlocale: pt-PT
  ms.lasthandoff: 09/01/2020
  ms.locfileid: "935572"
name: Microsoft Application Virtualization 4.6
summary: >+
  A vMicrosoft Application Virtualization 4.6 segue a Política de Ciclo de Vida [Fixa](/lifecycle/policies/fixed).


  Isto aplica-se às seguintes edições: para Serviços de Desktop Remoto, para Windows Desktops, Sequencer

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Ligações \n* [Informação sobre o produto e migração](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Orientações sobre migração](https://techcommunity.microsoft.com/t5/Product-Life-Cycle/FAST-products-approaching-the-end-of-extended-support-in-2018/td-p/101710)\n* [Política do service pack](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Como o cliente App-V 4.6 utiliza o App-V 4.5 Server, o App-V 4.5 Server continuará a ser suportado de acordo com as datas do ciclo de vida do App-V 4.6 quando for usado com o cliente App-V 4.6 suportado.\n\n## <a name=\"editions\"></a>Edições \n* para Serviços de Desktop Remoto\n* para Windows Desktops\n* Sequencer"
