### YamlMime:Lifecycle
metadata:
  title: Gestor de Configuração do Microsoft System Center 2012
  description: O Gestor de Configuração do Microsoft System Center 2012 segue a Política de Ciclo de Vida Fixa.
  ms.date: 03/12/2021
  keywords: null
name: Gestor de Configuração do Microsoft System Center 2012
summary: |+
  O Gestor de Configuração do Microsoft System Center 2012 segue a Política de Ciclo de Vida [Fixa](/lifecycle/policies/fixed).


products:
  - msc
policyType: fixed
supportDates:
  start: 05/30/2012
  end: 07/11/2017
  extendedEnd: 07/12/2022
releases:
  - version: Service Pack 2
    startDate: 05/12/2015
    endDate: 07/12/2022
  - version: Service Pack 1
    startDate: 12/15/2012
    endDate: 07/12/2016
  - version: Original Release
    startDate: 05/30/2012
    endDate: 01/14/2014
content: |+

  ## <a name="links"></a>Ligações 
  * [Política do service pack](/lifecycle/policies/fixed#service-packs)
  * [Documentação do System Center](/system-center/#pivot=components&panel=components-all)
  * [Recursos do System Center](https://www.microsoft.com/system-center/resources)
  * [Orientações sobre migração](https://techcommunity.microsoft.com/t5/configuration-manager-blog/system-center-2012-configuration-manager-is-approaching-end-of/ba-p/1650899)