### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007
  description: O Microsoft System Center Configuration Manager 2007 segue a Política de Ciclo de Vida Fixa.
  ms.date: 07/28/2020
  ms.openlocfilehash: 1b1f1b01df25eb733d93d618831fa157855d5318
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: pt-PT
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4144130"
name: Microsoft System Center Configuration Manager 2007
summary: >
  O Microsoft System Center Configuration Manager 2007 segue a Política de Ciclo de Vida [Fixa](/lifecycle/policies/fixed).



  > [!IMPORTANT]

  > O suporte para este produto terminou. Ver abaixo as orientações sobre migração.
products:
- msc
policyType: fixed
supportDates:
  start: 2007-11-29T00:00:00.000-08:00
  end: 2014-07-08T22:59:59.999-08:00
  extendedEnd: 2019-07-09T22:59:59.999-08:00
releases:
- version: Service Pack 2
  startDate: 2009-10-22T00:00:00.000-08:00
  endDate: 2019-07-09T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2008-05-21T00:00:00.000-08:00
  endDate: 2011-01-11T22:59:59.999-08:00
- version: Original Release
  startDate: 2007-11-29T00:00:00.000-08:00
  endDate: 2009-07-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Ligações \n* [Orientações sobre migração](/mem/configmgr/core/migration/migrate-data-between-hierarchies)\n* [Informações sobre produtos](/mem/configmgr/core/understand/introduction)\n* [Política do service pack](/lifecycle/policies/fixed#service-packs)"
