### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 5.0
  description: O Microsoft Application Virtualization 5.0 segue a Política de Ciclo de Vida Fixa.
  ms.date: 09/01/2020
  keywords: 'for Remote Desktop Services,for Terminal Services,for Windows Desktops'
name: Microsoft Application Virtualization 5.0
summary: |+
  O Microsoft Application Virtualization 5.0 segue a Política de Ciclo de Vida [Fixa](/lifecycle/policies/fixed).

  Isto aplica-se às seguintes edições: para Serviços de Ambiente de Trabalho Remoto, para Serviços de Terminal, para Windows Desktops

products:
  - windows
policyType: fixed
supportDates:
  start: 11/01/2012
  end: 01/09/2018
  extendedEnd: 01/10/2023
releases:
  - version: Service Pack 3
    startDate: 12/08/2014
    endDate: 01/10/2023
  - version: Service Pack 2
    startDate: 12/02/2013
    endDate: 01/12/2016
  - version: Service Pack 1
    startDate: 04/10/2013
    endDate: 01/13/2015
  - version: Original Release
    startDate: 11/01/2012
    endDate: 07/08/2014
content: |

  ## <a name="links"></a>Ligações 
  * [Informações sobre produtos](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)
  * [Política do service pack](/lifecycle/policies/fixed#service-packs)


  ## <a name="editions"></a>Edições 
  * para Serviços de Desktop Remoto
  * para Serviços de Terminal
  * para Windows Desktops