### YamlMime:Lifecycle
metadata:
  title: Microsoft System Center Configuration Manager 2007 R3
  description: O Microsoft System Center Configuration Manager 2007 R3 segue a Política de Ciclo de Vida Fixa.
  ms.date: 07/28/2020
name: Microsoft System Center Configuration Manager 2007 R3
summary: |
  O Microsoft System Center Configuration Manager 2007 R3 segue a Política de Ciclo de Vida [Fixa](/lifecycle/policies/fixed).


  > [!IMPORTANT]
  > O suporte para este produto terminou. Ver abaixo as orientações sobre migração.
products:
  - msc
policyType: fixed
supportDates:
  start: 12/19/2010
  end: 07/08/2014
  extendedEnd: 07/09/2019
releases:
  - version: Original Release
    startDate: 12/19/2010
    endDate: 07/09/2019
content: |+

  ## <a name="links"></a>Ligações 
  * [Orientações sobre migração](/mem/configmgr/core/migration/migrate-data-between-hierarchies)
  * [Orientações adicionais sobre migração](/mem/configmgr/core/migration/planning-for-migration)