### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.6 para Ambientes de Trabalho Windows
  description: O Microsoft Application Virtualization Hosting 4.6 para Ambientes de Trabalho do Windows segue a Política de Ciclo de Vida Fixa.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
name: Microsoft Application Virtualization Hosting 4.6 para Ambientes de Trabalho Windows
summary: |+
  O Microsoft Application Virtualization Hosting 4.6 para Ambientes de Trabalho do Windows segue a Política de Ciclo de Vida [Fixa](/lifecycle/policies/fixed).

  Isto aplica-se às seguintes edições: para Ambientes de Trabalho do Windows

products:
  - windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
  - version: Service Pack 3
    startDate: 12/02/2013
    endDate: 07/14/2020
  - version: Service Pack 2
    startDate: 10/01/2012
    endDate: 01/13/2015
  - version: Service Pack 1
    startDate: 01/26/2011
    endDate: 10/08/2013
  - version: Original Release
    startDate: 05/27/2010
    endDate: 04/10/2012
content: |

  ## <a name="links"></a>Ligações 
  * [Informação sobre o produto e migração](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)
  * [Política do service pack](/lifecycle/policies/fixed#service-packs)

  > [!NOTE]
  > Como o cliente App-V 4.6 utiliza o App-V 4.5 Server, o App-V 4.5 Server continuará a ser suportado de acordo com as datas do ciclo de vida do App-V 4.6 quando for usado com o cliente App-V 4.6 suportado.

  ## <a name="editions"></a>Edições 
  * para Windows Desktops