### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization 5.0
  description: O Microsoft Application Virtualization 5.0 segue a Política de Ciclo de Vida Fixa.
  ms.date: 09/01/2020
  keywords: for Remote Desktop Services,for Terminal Services,for Windows Desktops
  ms.openlocfilehash: 6f4b9be47350fce8f81af5516776520ac293cadc
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: pt-PT
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4139764"
name: Microsoft Application Virtualization 5.0
summary: >+
  O Microsoft Application Virtualization 5.0 segue a Política de Ciclo de Vida [Fixa](/lifecycle/policies/fixed).


  Isto aplica-se às seguintes edições: para Serviços de Ambiente de Trabalho Remoto, para Serviços de Terminal, para Windows Desktops

products:
- windows
policyType: fixed
supportDates:
  start: 2012-11-01T00:00:00.000-08:00
  end: 2018-01-09T22:59:59.999-08:00
  extendedEnd: 2023-01-10T22:59:59.999-08:00
releases:
- version: Service Pack 3
  startDate: 2014-12-08T00:00:00.000-08:00
  endDate: 2023-01-10T22:59:59.999-08:00
- version: Service Pack 2
  startDate: 2013-12-02T00:00:00.000-08:00
  endDate: 2016-01-12T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2013-04-10T00:00:00.000-08:00
  endDate: 2015-01-13T22:59:59.999-08:00
- version: Original Release
  startDate: 2012-11-01T00:00:00.000-08:00
  endDate: 2014-07-08T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Ligações \n* [Informações sobre produtos](/microsoft-desktop-optimization-pack/appv-v5/microsoft-application-virtualization-50-administrators-guide)\n* [Política do service pack](/lifecycle/policies/fixed#service-packs)\n\n\n## <a name=\"editions\"></a>Edições \n* para Serviços de Desktop Remoto\n* para Serviços de Terminal\n* para Windows Desktops"
