### YamlMime:Lifecycle
metadata:
  title: Virtualização da Aplicação Microsoft 4.6
  description: A Virtualização da Aplicação microsoft 4.6 segue a Política de Ciclo de Vida Fixo.
  ms.date: 07/28/2020
  ms.openlocfilehash: 868274b4468e663afe8e1b9f36069490ab4da025
  ms.sourcegitcommit: 9bdc77ca92cba2e3edb432e57b1845247a9ade6e
  ms.translationtype: MT
  ms.contentlocale: pt-PT
  ms.lasthandoff: 07/28/2020
  ms.locfileid: "833478"
name: Virtualização da Aplicação Microsoft 4.6
summary: >+
  A Virtualização da Aplicação microsoft 4.6 segue a Política de Ciclo de Vida [Fixo.](/lifecycle/policies/fixed)


  Isto aplica-se às seguintes edições: para Serviços remotos de Desktop, para Desktops Windows, Seqüestrador

products:
- windows
policyType: fixed
supportDates:
  start: 05/27/2010
  end: 07/14/2015
  extendedEnd: 07/14/2020
releases:
- version: Service Pack 3
  startDate: 12/02/2013
  endDate: 07/14/2020
- version: Service Pack 2
  startDate: 10/01/2012
  endDate: 01/13/2015
- version: Service Pack 1
  startDate: 01/26/2011
  endDate: 10/08/2013
- version: Original Release
  startDate: 05/27/2010
  endDate: 04/10/2012
content: "\n## <a name=\"links\"></a>Links \n* [Informações sobre produtos e migrações](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Orientação para a migração](https://techcommunity.microsoft.com/t5/Product-Life-Cycle/FAST-products-approaching-the-end-of-extended-support-in-2018/td-p/101710)\n* [Política de pacote de serviço](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Uma vez que o cliente App-V 4.6 utiliza o Servidor App-V 4.5, o Servidor App-V 4.5 continuará a ser suportado de acordo com as datas do ciclo de vida do App-V 4.6 quando em uso com o cliente app-V 4.6 suportado.\n\n## <a name=\"editions\"></a>Edições \n* para serviços de desktop remoto\n* para desktops windows\n* Sequenciador"
