### YamlMime:Lifecycle
metadata:
  title: Microsoft Forefront Client Security
  description: O Microsoft Forefront Client Security segue a Política de Ciclo de Vida Fixa.
  ms.date: 08/28/2020
  ms.openlocfilehash: d85aea21441458397839241e74939536051397d4
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: pt-PT
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4113420"
name: Microsoft Forefront Client Security
summary: >+
  O Microsoft Forefront Client Security segue a Política de Ciclo de Vida [Fixa](/lifecycle/policies/fixed).


products:
- msc
policyType: fixed
supportDates:
  start: 2007-08-02T00:00:00.000-08:00
  extendedEnd: 2015-07-14T22:59:59.999-08:00
releases:
- version: Original Release
  startDate: 2007-08-02T00:00:00.000-08:00
  endDate: 2015-07-14T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Ligações \n* [System Center Endpoint Protection](/lifecycle/products/microsoft-system-center-2012-endpoint-protection)\n\n> [!NOTE]\n> O Forefront Client Security foi descontinuado a 14 de julho de 2015. As atualizações de definição de Antimalware e Antispyware deixarão de estar disponíveis após o fim do suporte para a versão do produto. Pondere utilizar o System Center Endpoint Protection como um substituto."
