### YamlMime:Lifecycle
metadata:
  title: Virtualização da aplicação microsoft hospedagem 5.0 para desktops windows
  description: O Microsoft Application Virtualization Hosting 5.0 para Windows Desktops segue a Política de Ciclo de Vida Fixo.
  ms.date: 07/28/2020
  ms.openlocfilehash: dff04b865491bfb99aa8d20e556aafd434a59398
  ms.sourcegitcommit: 6b0f0d4ac042ba924016a386cd23db5f1ed22756
  ms.translationtype: MT
  ms.contentlocale: pt-PT
  ms.lasthandoff: 07/29/2020
  ms.locfileid: "860427"
name: Virtualização da aplicação microsoft hospedagem 5.0 para desktops windows
summary: >+
  O Microsoft Application Virtualization Hosting 5.0 para Windows Desktops segue a Política de Ciclo de Vida [Fixo.](/lifecycle/policies/fixed)


  Isto aplica-se às seguintes edições: para desktops windows

products:
- windows
policyType: fixed
supportDates:
  start: 11/01/2012
  end: 01/09/2018
  extendedEnd: 04/14/2026
releases:
- version: Service Pack 3
  startDate: 12/08/2014
  endDate: 04/14/2026
- version: Service Pack 2
  startDate: 11/08/2013
  endDate: 01/12/2016
- version: Service Pack 1
  startDate: 04/10/2013
  endDate: 01/13/2015
- version: Original Release
  startDate: 11/01/2012
  endDate: 07/08/2014
content: "\n## <a name=\"links\"></a>Links \n* [Informações sobre o produto](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Política de pacote de serviço](/lifecycle/policies/fixed#service-packs)\n\n\n## <a name=\"editions\"></a>Edições \n* para desktops windows"
