### YamlMime:Lifecycle
metadata:
  title: Microsoft Application Virtualization Hosting 4.6 para Ambientes de Trabalho Windows
  description: O Microsoft Application Virtualization Hosting 4.6 para Ambientes de Trabalho do Windows segue a Política de Ciclo de Vida Fixa.
  ms.date: 09/01/2020
  keywords: for Windows Desktops
  ms.openlocfilehash: 3d5789104bc3b52d4ccfb836df52ddd2ab576d4e
  ms.sourcegitcommit: 2bcdf249c9ef19aab3355f7dff4e0e020252ff76
  ms.translationtype: HT
  ms.contentlocale: pt-PT
  ms.lasthandoff: 03/18/2022
  ms.locfileid: "4153935"
name: Microsoft Application Virtualization Hosting 4.6 para Ambientes de Trabalho Windows
summary: >+
  O Microsoft Application Virtualization Hosting 4.6 para Ambientes de Trabalho do Windows segue a Política de Ciclo de Vida [Fixa](/lifecycle/policies/fixed).


  Isto aplica-se às seguintes edições: para Ambientes de Trabalho do Windows

products:
- windows
policyType: fixed
supportDates:
  start: 2010-05-27T00:00:00.000-08:00
  end: 2015-07-14T22:59:59.999-08:00
  extendedEnd: 2020-07-14T22:59:59.999-08:00
releases:
- version: Service Pack 3
  startDate: 2013-12-02T00:00:00.000-08:00
  endDate: 2020-07-14T22:59:59.999-08:00
- version: Service Pack 2
  startDate: 2012-10-01T00:00:00.000-08:00
  endDate: 2015-01-13T22:59:59.999-08:00
- version: Service Pack 1
  startDate: 2011-01-26T00:00:00.000-08:00
  endDate: 2013-10-08T22:59:59.999-08:00
- version: Original Release
  startDate: 2010-05-27T00:00:00.000-08:00
  endDate: 2012-04-10T22:59:59.999-08:00
content: "\n## <a name=\"links\"></a>Ligações \n* [Informação sobre o produto e migração](/microsoft-desktop-optimization-pack/appv-v4/overview-of-application-virtualization)\n* [Política do service pack](/lifecycle/policies/fixed#service-packs)\n\n> [!NOTE]\n> Como o cliente App-V 4.6 utiliza o App-V 4.5 Server, o App-V 4.5 Server continuará a ser suportado de acordo com as datas do ciclo de vida do App-V 4.6 quando for usado com o cliente App-V 4.6 suportado.\n\n## <a name=\"editions\"></a>Edições \n* para Windows Desktops"
