### YamlMime:Lifecycle
metadata:
  title: SoftGrid Application Virtualization
  description: O SoftGrid Application Virtualization segue a Política de Ciclo de Vida Fixa.
  ms.date: 09/10/2020
  keywords: 4.1 for Desktops,4.2 for Desktops,for Terminal Services 4.1
  ms.openlocfilehash: 5009a44f0d0ab2b180f62474de8f4d4bb01e3e62
  ms.sourcegitcommit: c0c65f657b1da8e588fda5bedd3572fb2e3168bc
  ms.translationtype: HT
  ms.contentlocale: pt-PT
  ms.lasthandoff: 09/10/2020
  ms.locfileid: "1001031"
name: SoftGrid Application Virtualization
summary: >
  O SoftGrid Application Virtualization segue a Política de Ciclo de Vida [Fixa](/lifecycle/policies/fixed).


  Isto aplica-se às seguintes edições: 4.1 para Desktops, 4.2 para Desktops, para Serviços de Terminal 4.1


  > [!IMPORTANT]

  > O suporte terminou. Ver abaixo as orientações sobre migração.
products:
- windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
- version: Original Release
  startDate: 05/25/2007
  endDate: 07/11/2017
content: "\n## <a name=\"links\"></a>Ligações \n* [Orientações sobre migração](https://technet.microsoft.com/en-us/windows/bb899442)\n\n\n## <a name=\"editions\"></a>Edições \n* 4.1 para Desktops\n* 4.2 para Desktops\n* para Serviços de Terminal 4.1"
