### YamlMime:Lifecycle
metadata:
  title: SoftGrid Application Virtualization
  description: O SoftGrid Application Virtualization segue a Política de Ciclo de Vida Fixa.
  ms.date: 09/10/2020
  keywords: '4.1 for Desktops,4.2 for Desktops,for Terminal Services 4.1'
name: SoftGrid Application Virtualization
summary: |
  O SoftGrid Application Virtualization segue a Política de Ciclo de Vida [Fixa](/lifecycle/policies/fixed).

  Isto aplica-se às seguintes edições: 4.1 para Desktops, 4.2 para Desktops, para Serviços de Terminal 4.1

  > [!IMPORTANT]
  > O suporte terminou. Ver abaixo as orientações sobre migração.
products:
  - windows
policyType: fixed
supportDates:
  start: 05/25/2007
  end: 07/10/2012
  extendedEnd: 07/11/2017
releases:
  - version: Original Release
    startDate: 05/25/2007
    endDate: 07/11/2017
content: |

  ## <a name="links"></a>Ligações 
  * [Orientações sobre migração](https://technet.microsoft.com/en-us/windows/bb899442)


  ## <a name="editions"></a>Edições 
  * 4.1 para Desktops
  * 4.2 para Desktops
  * para Serviços de Terminal 4.1